import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  definitions: [{type: 'autogenerated', dirName: './definitions'}],
};

export default sidebars;
