import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  directory: [{type: 'autogenerated', dirName: '.'}],
  resources: [{type: 'autogenerated', dirName: 'Resources'}],
  robotics0: [{type: 'autogenerated', dirName: 'Robotics & Mechatronics Pre-Introduction'}],
  robotics1: [{type: 'autogenerated', dirName: 'Robotics & Mechatronics I'  }],
  robotics2: [{type: 'autogenerated', dirName: 'Robotics & Mechatronics II' }],
  robotics3: [{type: 'autogenerated', dirName: 'Robotics & Mechatronics III'}],
  robotics4: [{type: 'autogenerated', dirName: 'Robotics & Mechatronics IV' }], 
  glossary : [{type: 'autogenerated', dirName: 'Glossary'}],
};

export default sidebars;
