import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  robotics0  : [{type: 'autogenerated', dirName: 'Robotics & Mechatronics Pre-Introduction'}],
  robotics1  : [{type: 'autogenerated', dirName: 'Robotics & Mechatronics I'  }],
  robotics2  : [{type: 'autogenerated', dirName: 'Robotics & Mechatronics II' }],
  robotics3  : [{type: 'autogenerated', dirName: 'Robotics & Mechatronics III'}],
  robotics4  : [{type: 'autogenerated', dirName: 'Robotics & Mechatronics IV' }],
  definitions: [{type: 'autogenerated', dirName: 'Definitions'}],
};

export default sidebars;
